// 最后更新于 2025-12-16 13:28:36
const musicData = [
    {
        "id": 170,
        "title": "Seht auf die breiten",
        "composer": "Franz Joseph Haydn/海顿",
        "work": "Die Jahreszeiten, Hob. XXI:3/ 四季",
        "language": "德语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音",
        "tonality": "",
        "description": "清唱剧四季选段",
        "filename": "宗教声乐作品/1765916891.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 169,
        "title": "Schon eilet froh der ackersmann",
        "composer": "Franz Joseph Haydn/海顿",
        "work": " Die Jahreszeiten, Hob. XXI:3/四季",
        "language": "德语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音",
        "tonality": "",
        "description": "清唱剧四季选段",
        "filename": "宗教声乐作品/1765916813.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 168,
        "title": "Rolling in foaming",
        "composer": "Franz Joseph Haydn/海顿",
        "work": "The Creation, Hob. XXI:2/创世纪",
        "language": "英语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音或Baritone/男中音",
        "tonality": "",
        "description": "清唱剧创世纪选段",
        "filename": "宗教声乐作品/1765916728.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 167,
        "title": "And God Made The Firmament",
        "composer": "Franz Joseph Haydn/海顿",
        "work": "The Creation, Hob. XXI:2/创世纪",
        "language": "英语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音或Baritone/男中音",
        "tonality": "",
        "description": "清唱剧创世纪选段",
        "filename": "宗教声乐作品/1765916689.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 166,
        "title": "Komm, süßer tod, BWV 478",
        "composer": "J.S. Bach/巴赫",
        "work": "",
        "language": "德语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音或Baritone/男中音",
        "tonality": "",
        "description": "",
        "filename": "宗教声乐作品/1765916524.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 165,
        "title": "Mache dich mein herze rein",
        "composer": "J.S. Bach/巴赫",
        "work": "Matthäuspassion, BWV 244/马太受难曲",
        "language": "德语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音",
        "tonality": "",
        "description": "",
        "filename": "宗教声乐作品/1765916467.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 164,
        "title": "Komm Süßes Kreuz",
        "composer": "J.S. Bach/巴赫",
        "work": "Matthäuspassion, BWV 244/马太受难曲",
        "language": "德语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音",
        "tonality": "",
        "description": "",
        "filename": "宗教声乐作品/1765916444.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 163,
        "title": "Gebt mir meinen Jesum wieder",
        "composer": "J.S. Bach/巴赫",
        "work": "Matthäuspassion, BWV 244/马太受难曲",
        "language": "德语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音",
        "tonality": "",
        "description": "",
        "filename": "宗教声乐作品/1765916400.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 162,
        "title": "Et in Spritm Sanctum",
        "composer": "J.S. Bach/巴赫",
        "work": "Mass in B minor, BWV 232",
        "language": "德语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass-Baritone/低男中音或Baritone/男中音",
        "tonality": "",
        "description": "",
        "filename": "宗教声乐作品/1765916249.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 161,
        "title": "Belsazar, Op.57",
        "composer": "Robert Schumann/舒曼",
        "work": "",
        "language": "德语",
        "category": "艺术歌曲",
        "voice_count": "",
        "voice_types": "",
        "tonality": "降A大调",
        "description": "",
        "filename": "艺术歌曲/1765904516.pdf",
        "date": "2025-12-16",
        "has_lyrics": true
    },
    {
        "id": 160,
        "title": "Die beiden Grenadiere/两个禁卫军/两个掷弹兵",
        "composer": "Richard Wagner/瓦格纳",
        "work": "Les deux grenadiers, WWV 60",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "description": "",
        "filename": "歌剧咏叹调/1765904235.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 159,
        "title": "Am meer/在海边",
        "composer": "Franz Schubert/舒伯特",
        "work": "Schwanengesang, D.957",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "",
        "tonality": "降A大调",
        "description": "",
        "filename": "歌剧咏叹调/1765904089.pdf",
        "date": "2025-12-16",
        "has_lyrics": false
    },
    {
        "id": 158,
        "title": "The House of Life/生命之屋",
        "composer": "Ralph Vaughan Williams/沃恩·威廉姆斯",
        "work": "",
        "language": "英语",
        "category": "声乐套曲",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "声乐套曲/1765779692.pdf",
        "date": "2025-12-14",
        "has_lyrics": false,
        "description": "1. Love Sight\r\n2. Silent Noon\r\n3. Love's Minstrels\r\n4. Heart's Haven\r\n5. Death in Love\r\n6. Love's Last Gift"
    },
    {
        "id": 157,
        "title": "Ten Blake Songs",
        "composer": "Ralph Vaughan Williams/沃恩·威廉姆斯",
        "work": "",
        "language": "英语",
        "category": "声乐套曲",
        "voice_count": "",
        "voice_types": "人声与双簧管",
        "tonality": "",
        "filename": "声乐套曲/1765779618.pdf",
        "date": "2025-12-14",
        "has_lyrics": false,
        "description": "Infant Joy no.1\r\nA Poison Tree no.2\r\nThe Piper no.3\r\nLondon no.4\r\nThe Lamb no.5\r\nThe Shepherd no.6\r\nAh, sunflower no.7\r\nCruelty has a human heart no.8\r\nThe Divine Image no.9\r\nEternity no.10"
    },
    {
        "id": 156,
        "title": "A Shropshire Lad/什罗普郡小伙子",
        "composer": "George Butterworth",
        "work": "",
        "language": "英语",
        "category": "声乐套曲",
        "voice_count": "",
        "voice_types": "",
        "tonality": "降调",
        "filename": "声乐套曲/1765779501.pdf",
        "date": "2025-12-14",
        "has_lyrics": false,
        "description": "1. Loveliest of trees\r\n2. When I was one-and-twenty\r\n3. Look not in my eyes\r\n4. Think no more, lad\r\n5. The lads in their hundreds\r\n6. Is my team ploughing?"
    },
    {
        "id": 155,
        "title": "Henry Purcell Songs/普赛尔歌曲集",
        "composer": "Henry Purcell/普赛尔",
        "work": "",
        "language": "英语",
        "category": "乐谱书/曲集",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "乐谱书/曲集/1765779072.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 154,
        "title": "A Young Man's Exhortation",
        "composer": "Gerald Finzi",
        "work": "",
        "language": "英语",
        "category": "声乐套曲",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "声乐套曲/1765778980.pdf",
        "date": "2025-12-14",
        "has_lyrics": false,
        "description": "1. A young man's exhortation\r\n2. Budmouth Dears\r\n3. Ditty\r\n4. Her temple\r\n5. The Comet at Yell'ham\r\n6. Shortening days\r\n7. The sigh\r\n8. Former beauties\r\n9. Transformations\r\n10. The dance continued"
    },
    {
        "id": 153,
        "title": "Baber歌曲集",
        "composer": "Samuel Barber",
        "work": "",
        "language": "英语",
        "category": "乐谱书/曲集",
        "voice_count": "",
        "voice_types": "高声部",
        "tonality": "",
        "filename": "乐谱书/曲集/1765778795.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 152,
        "title": "Let us garlands bring",
        "composer": "Gerald Finzi",
        "work": "",
        "language": "英语",
        "category": "声乐套曲",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "声乐套曲/1765778479.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 151,
        "title": "Ives 114 Songs",
        "composer": "Charles Ives",
        "work": "",
        "language": "英语",
        "category": "乐谱书/曲集",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "乐谱书/曲集/1765778386.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 150,
        "title": "Songs of Travel/旅行之歌",
        "composer": "Ralph Vaughan Williams/沃恩·威廉姆斯",
        "work": "",
        "language": "英语",
        "category": "声乐套曲",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "声乐套曲/1765778286.pdf",
        "date": "2025-12-14",
        "has_lyrics": false,
        "description": "1. The vagabond\r\n2. Let Beauty awake\r\n3. The roadside fire\r\n4. Youth and love\r\n5. In dreams\r\n6. The infinite shining heavens\r\n7. Whither must I wander?\r\n8. Bright is the ring of words\r\n9. I have trod the upward and the downward slope"
    },
    {
        "id": 149,
        "title": "Sono all'ara…barriera tremenda…Ciel pietoso, in sì crudo momento",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La straniera",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777839.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 148,
        "title": "Or sei pago, o ciel tremendo",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La straniera",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777819.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 147,
        "title": "Sventurata, anch'io deliro",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Il Pirata/海盗",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777799.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 146,
        "title": "Lo sognai ferito, esangue",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Il Pirata/海盗",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777781.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 145,
        "title": "Col sorriso d'innocenza",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Il Pirata/海盗",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777765.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 144,
        "title": "La mia scelta a voi sia grata… Contenta appien quest'alma",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Bianca e Fernando (Bianca e Gernando)",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777733.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 143,
        "title": "Deh! Non ferir… Alla gioia ed al piacer",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Bianca e Fernando (Bianca e Gernando)",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777715.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 142,
        "title": "Oh! Mie fedeli!...Ma la sola, ohimè! son io…Ah! La pena in lor piombò",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Beatrice di Tenda",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777690.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 141,
        "title": "Dopo l'oscuro nembo",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Adelson e Salvini",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777652.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 140,
        "title": "È serbato, a questo acciaro",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Capuleti ed i Montecchi",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777584.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 139,
        "title": "Ah! Se non m'ami piu",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La straniera",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Mezzo Soprano/次女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777534.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 138,
        "title": "Tu sola… Deh! Tu, deh! Tu, bell'anima",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Capuleti ed i Montecchi",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Mezzo Soprano/次女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777504.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 137,
        "title": "Se Romeo l'uccise un figlio",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Capuleti ed i Montecchi",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Mezzo Soprano/次女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777478.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 136,
        "title": "Tutto è gioia, tutto è festa",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777414.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 135,
        "title": "De' lieti auguri a voi",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777398.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 134,
        "title": "Sovra il sen la man mi posa",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777369.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 133,
        "title": "Care compagne… Come per me serena",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777347.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 132,
        "title": "Ah! Non giunge uman pensiero",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777322.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 131,
        "title": "Ah! non credea mirarti",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777279.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 130,
        "title": "Son vergin vezzosa",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777263.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 129,
        "title": "Qui la voce… Vien, diletto",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777208.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 128,
        "title": "Morte io non temo",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Capuleti ed i Montecchi",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777178.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 127,
        "title": "Eccomi in lieta vesta…Oh quante volte ti chiedo",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Capuleti ed i Montecchi",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Coloratura/花腔女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765777140.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 126,
        "title": "Vi ravviso, o luoghi ameni",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776810.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 125,
        "title": "Tu non sai conquei begli occhi",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776786.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 124,
        "title": "Cinta di fiori",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776752.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 123,
        "title": "Vieni, vieni fra questa braccia",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776611.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 122,
        "title": "Sprezzo, audace, il tuo furore",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776583.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 121,
        "title": "Son salvo...La mia canzon d'amore…Ad altro lato",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776560.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 120,
        "title": "Credeasi, misera",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776539.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 119,
        "title": "A te, o cara, amor talora",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776515.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 118,
        "title": "Ah! perchè non posso odiarti",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776446.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 117,
        "title": "Prendi: I'anel ti dono",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776378.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 116,
        "title": "Tu vedrai la sventurata",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Il Pirata/海盗",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776348.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 115,
        "title": "Per te di vane lagrime",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Il Pirata/海盗",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776324.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 114,
        "title": "Nel furor delle tempeste",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Il Pirata/海盗",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776304.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 113,
        "title": "All'udir del padre afflitto… Odo il tuo pianto",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Bianca e Fernando (Bianca e Gernando)",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765776244.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 112,
        "title": "All'udir del padre afflitto… Odo il tuo pianto",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Bianca e Fernando (Bianca e Gernando)",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765775472.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 111,
        "title": "A tanto duol…Ascolta, o padre",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Bianca e Fernando (Bianca e Gernando)",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765775443.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 110,
        "title": "Meco all'altar di Venere… Me protegge, me difende",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Norma/诺玛/诺尔玛",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Tenor/男高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765775410.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 109,
        "title": "Qual cor tradisti, qual cor perdesti… Deh! Non volerli vittime",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Norma/诺玛/诺尔玛",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765775364.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 108,
        "title": "Casta Diva, che inargenti… Ah! Bello a me ritorna/圣洁的女神",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Norma/诺玛/诺尔玛",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Soprano/女高音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765775251.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 107,
        "title": "Taci, attendi, e allor vedrai",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Adelson e Salvini",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765775176.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 106,
        "title": "Bonifacio Beccheria qui presente",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Adelson e Salvini",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765775152.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 105,
        "title": "Ferma! Invan, invan rapir pretendi",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765775044.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 104,
        "title": "Allor che notte avanza… Bramato momento",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Bianca e Fernando (Bianca e Gernando)",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774953.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 103,
        "title": "Ah no, si licia sorte… O contento",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Bianca e Fernando (Bianca e Gernando)",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774879.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 102,
        "title": "Da gelido sudore",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Bianca e Fernando (Bianca e Gernando)",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774849.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 101,
        "title": "Io provo un palpito per tal dimora",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Adelson e Salvini",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774797.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 100,
        "title": "Ehi! Geronio!",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Adelson e Salvini",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774769.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 99,
        "title": "Si li sciogliete, o giudici",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La straniera",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774697.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 98,
        "title": "Qui m'accolse oppresso, errante",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Beatrice di Tenda",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774651.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 97,
        "title": "Rimorso in lei",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Beatrice di Tenda",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774570.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 96,
        "title": "Il mulino il fonte il bosco",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "La Sonnambula/梦游女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774343.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 95,
        "title": "Si vinceremo e il pregio io sento",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "Il Pirata/海盗",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774243.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 94,
        "title": "Se il cor guerriero",
        "composer": "Antonio Vivaldi/维瓦尔第",
        "work": "Tito Manlio, RV 738",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass-Baritone/低男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765774083.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 93,
        "title": "Batter my heart",
        "composer": "John Adams/约翰·亚当斯",
        "work": "Dr. Atomic/原子博士",
        "language": "英语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765773684.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 92,
        "title": "You rascal, you! I never knew you had a soul",
        "composer": "Samuel Barber",
        "work": "Vanessa",
        "language": "English",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/1765773474.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 91,
        "title": "Soave sia il vento",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Così fan tutte, K. 588/女人心",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "三重唱",
        "voice_types": "Bass / Soprano / Mezzo-Soprano",
        "tonality": "",
        "filename": "歌剧重唱/1765773156.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 90,
        "title": "O statua gentilissima",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Don Giovanni, K527/唐璜",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "二重唱",
        "voice_types": "Bass-Baritone / Baritone",
        "tonality": "",
        "filename": "歌剧重唱/1765773074.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 89,
        "title": "Eh! via buffone",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Don Giovanni, K527/唐璜",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "二重唱",
        "voice_types": "Bass-Baritone / Baritone",
        "tonality": "",
        "filename": "歌剧重唱/1765773009.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 88,
        "title": "Se a caso madama",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Le Nozze di Figaro, K.492/费加罗的婚礼",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "二重唱",
        "voice_types": "Soprano / Bass-Baritone",
        "tonality": "",
        "filename": "歌剧重唱/1765772774.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 87,
        "title": "Pa-Pa-Pa-Papageno",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Die Zauberflöte, K.620/魔笛",
        "language": "德语",
        "category": "歌剧重唱",
        "voice_count": "二重唱",
        "voice_types": "Soprano / Baritone",
        "tonality": "",
        "filename": "歌剧重唱/1765772301.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 86,
        "title": "Cinque...dieci...venti",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Le Nozze di Figaro, K.492/费加罗的婚礼",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "二重唱",
        "voice_types": "Bass-Baritone / Soprano",
        "tonality": "",
        "filename": "歌剧咏叹调/1765771966.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 85,
        "title": "Là ci darem la mano/让我们携手同行",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Don Giovanni, K527/唐璜",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "二重唱",
        "voice_types": "Soprano / Baritone",
        "tonality": "",
        "filename": "歌剧咏叹调/1765771793.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 84,
        "title": "A Sea Symphony/大海交响曲",
        "composer": "Ralph Vaughan Williams/沃恩·威廉姆斯",
        "work": "",
        "language": "英语",
        "category": "管弦乐/交响曲",
        "voice_count": "",
        "voice_types": "SB独唱与SATB合唱与管弦乐队",
        "tonality": "",
        "filename": "管弦乐/交响曲/1765769768.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 83,
        "title": "Sonata No.3 Op.25/奏鸣曲",
        "composer": "Erich Wolfgang Korngold/科恩戈尔德",
        "work": "",
        "language": "",
        "category": "器乐独奏",
        "voice_count": "",
        "voice_types": "钢琴独奏",
        "tonality": "C大调",
        "filename": "器乐独奏/1765769408.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 82,
        "title": "Ave Verum Corpus, K.618",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "",
        "language": "拉丁语",
        "category": "合唱作品",
        "voice_count": "",
        "voice_types": "SATB",
        "tonality": "D大调",
        "filename": "合唱作品/1765769228.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 81,
        "title": "罗忠镕艺术歌曲集",
        "composer": "罗忠镕",
        "work": "",
        "language": "汉语",
        "category": "乐谱书/曲集",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "乐谱书/曲集/1765768954.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 80,
        "title": "A Shropshire Lad/什罗普郡小伙子",
        "composer": "George Butterworth",
        "work": "",
        "language": "英语",
        "category": "声乐套曲",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "声乐套曲/1765768898.pdf",
        "date": "2025-12-14",
        "has_lyrics": false,
        "description": "1. Loveliest of trees\r\n2. When I was one-and-twenty\r\n3. Look not in my eyes\r\n4. Think no more, lad\r\n5. The lads in their hundreds\r\n6. Is my team ploughing?"
    },
    {
        "id": 79,
        "title": "Le Nozze di Figaro, K.492/费加罗的婚礼",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "",
        "language": "意大利语",
        "category": "歌剧总谱",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "歌剧总谱/1765739733.pdf",
        "date": "2025-12-14",
        "has_lyrics": true
    },
    {
        "id": 78,
        "title": "Warm as the Autumn Light",
        "composer": "Douglas Stuart Moore",
        "work": "The Ballad of Baby Doe",
        "language": "英语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Warm_as_the_Autumn_Light-The_Ballad_of_Baby_Doe.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 77,
        "title": "Votre toast (Toreador Song)/斗牛士之歌",
        "composer": "Georges Bizet/比才",
        "work": "Carmen/卡门",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass-Baritone/低男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Votre_toast_je_peux_vous_le_rendre_Toreador_Song-Carmen.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 76,
        "title": "Vision fugitive/短暂的幻影",
        "composer": "Jules Massenet/马斯奈",
        "work": "Hérodiade",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Vision_fugitive-Herodiade.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 75,
        "title": "Uzhel ta samaya Tatyana",
        "composer": "Pyotr Ilyich Tchaikovsky/柴可夫斯基",
        "work": "Eugene  Onegin/叶甫盖尼·奥涅金",
        "language": "俄语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Uzhel_ta_samaya_Tatyana-Eugene_Onegin.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 74,
        "title": "Their brains are boiled/他们的脑浆在沸腾",
        "composer": "Thomas adès",
        "work": "The Tempest/暴风雨",
        "language": "英语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Their_brains_are_boiled-The_Tempest.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 73,
        "title": "Starbuck's Aria",
        "composer": "Jake Heggie",
        "work": "Moby Dick",
        "language": "英语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Starbucks_Aria-Captain_Ahab_I_must_speak_with_you-Moby_Dick.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 72,
        "title": "Sorge infausta/刮起一阵不祥的暴风雨",
        "composer": "Georg Friedrich Händel/亨德尔",
        "work": "Orlando/奥兰多",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass-Baritone/低男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Sorge_infausta-Orlando.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 71,
        "title": "Sosi immobile",
        "composer": "Gioachino Rossini/罗西尼",
        "work": "Guillame Tell/威廉退尔",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Sois_immobile-Guillame_Tell.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 70,
        "title": "Sibilar gli angui d'Aletto",
        "composer": "Georg Friedrich Händel/亨德尔",
        "work": "Rinaldo/里纳尔多",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Sibilar_gli_angui_dAletto-Rinaldo.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 69,
        "title": "Si puo, Si puo/原谅，原谅",
        "composer": "Ruggero Leoncavallo/莱昂卡瓦洛",
        "work": "Pagliacci/丑角",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Si_puo-Pagliacci.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 68,
        "title": "See the raging flames arise",
        "composer": "Georg Friedrich Händel/亨德尔",
        "work": "Joshua/约书亚",
        "language": "英语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass-Baritone/低男中音",
        "tonality": "",
        "filename": "宗教声乐作品/See_the_raging_flames_arise-Joshua.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 67,
        "title": "Scintille diamant",
        "composer": "Jacques Offenbach/奥芬巴赫",
        "work": "Les Contes d'Hoffmann/霍夫曼的故事",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Scintille_diamant-Les_Contes_Dhoffmann.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 66,
        "title": "Rivolgete a lui lo sguardo/转向她，注视她",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Così fan tutte, K.588/女人心",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Rivolgete_a_lui_lo_sguardo-Cosi_fan_tutte.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 65,
        "title": "Questo amor vergogna mia",
        "composer": "Giacomo Puccini/普契尼",
        "work": "Edgar/埃德加",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Questo_amor_vergogna_mia-Edgar.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 64,
        "title": "Per me giunto/我的末日就在眼前",
        "composer": "Giuseppe Verdi/威尔第",
        "work": "Don Carlo/唐卡洛",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Per_me_giunto-Don_Carlo.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 63,
        "title": "Papagena Papagena Papagena!",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Die Zauberflöte, K.620/魔笛",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/PapagenaPapagenaPapagena-Die_Zauberflote.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 62,
        "title": "O vin dissipe la tristesse/美酒驱散悲伤（饮酒歌）",
        "composer": "Ambroise Thomas/托玛",
        "work": "Hamlet/哈姆雷特",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/O_vin_dissipe_la_tristesse-Hamlet.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 61,
        "title": "O Lisbona, alfin ti miro",
        "composer": "Gaetano Donizetti/多尼采蒂",
        "work": "Don Sebastiano",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/O_Lisbona_alfin_ti_miro-_Don_Sebastiano.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 60,
        "title": "O du mein holder Abendstern/晚星颂",
        "composer": "Richard Wagner/瓦格纳",
        "work": "Tannhäuser/唐豪瑟",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/O_du_mein_holder_Abendstern-Tannhauser.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 59,
        "title": "Nulla! Silenzio",
        "composer": "Giacomo Puccini/普契尼",
        "work": "Il Tabarro/外套",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/NullaSilenzio-Il_Tabarro.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 58,
        "title": "Nemico della patria/他是祖国的敌人",
        "composer": "Umberto Giordano/乔尔达诺",
        "work": "Andrea Chénier/安德烈·谢尼埃",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Nemico_della_patria-Andrea_Chenier.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 57,
        "title": "Miei rampolli femminini",
        "composer": "Giaochino Rossini",
        "work": "La Cenerentola/灰姑娘",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Miei_rampolli_femminini-La_Cenerentola.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 56,
        "title": "Mein Sehnen mein Wähnen/我的思念，我的幻想",
        "composer": "Erich Korngold/科恩戈尔德",
        "work": "Die Tote Stadt",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Mein_Sehen_mein_Wahnen-Die_Tote_Stadt.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 55,
        "title": "Mab la reine des mensonges",
        "composer": "Charles Gounod/古诺",
        "work": "Romeo et Juilliette/罗密欧与朱丽叶",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Mab-Romeo_et_Juilliette.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 54,
        "title": "Look! Through the port",
        "composer": "Benjamin Britten/布里顿",
        "work": "Billy Budd/比利·巴德",
        "language": "英语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Look_Through_the_port-Billy_Budd.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 53,
        "title": "Largo al factotum/快给大忙人让路",
        "composer": "Gioachino Rossini/罗西尼",
        "work": "Il Barbiere di Sviglia/塞维利亚的理发师",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Largo_al_factotum-Il_Barbiere_di_Svigila.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 52,
        "title": "L'orage s'est calme",
        "composer": "Georges Bizet/比才",
        "work": "Les Pêcheurs de perles/采珠人",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Lorage_sest_calme-Les_Pecheurs_de_perles.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 51,
        "title": "Kogda bi zhizn domashnim krugom",
        "composer": "Pyotr Ilyich Tchaikovsky/柴可夫斯基",
        "work": "Eugene Onegin/叶甫盖尼·奥涅金",
        "language": "俄语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Kogda_bi_zhizn_domashnim_krugom-Eugene_Onegin.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 50,
        "title": "Kennst du das land",
        "composer": "Mark Adamo",
        "work": "Little Woman",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Kennst_du_das_land-Little_Woman.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 49,
        "title": "Ja vas lyublyu/我爱你",
        "composer": "Pyotr Ilyich Tchaikovsky/柴可夫斯基",
        "work": "Queen of Spades/黑桃皇后",
        "language": "俄语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Ja_vas_lyublyu-Queen_of_Spades.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 48,
        "title": "Hai gia vinta la causa/你已赢得了诉讼",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Le Nozze di Figaro, K.492/费加罗的婚礼",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Hai_gia_vintan_la_causa-Le_Nozze_di_Figaro.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 47,
        "title": "Ha! welch ein Augenblick",
        "composer": "Ludwig van Beethoven/贝多芬",
        "work": "Fidelio/费德里奥",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Ha_welch_ein_Augenblick-Fidelio.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 46,
        "title": "Fleuris sait une rose",
        "composer": "Jules Massenet/马斯奈",
        "work": "Le Jongleur De Notre Dame",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Fleuris_sait_une_rose-Le_jongleur_de_Notre-Dmae.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 45,
        "title": "Fin ch'han dal vino/让大家痛饮，让大家狂欢",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Don Giovanni, K.527/唐璜",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Fin_chhan_dal_vino-Don_Giovanni.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 44,
        "title": "Eri tu/你玷污了我的灵魂",
        "composer": "Giuseppe Verdi/威尔第",
        "work": "Un Ballo in Mascher/假面舞会",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Eri_tu-Un_Ballo_in_Maschera.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 43,
        "title": "Era eguale la voce",
        "composer": "Giacomo Puccini/普契尼",
        "work": "Gianni Schicchi/贾尼·斯基基",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Era_eguale_la_voce-Gianni_Schicchi.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 42,
        "title": "Ein Madchen oder Weibchen/愿姑娘或大嫂",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Die Zauberflöte, K.620/魔笛",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Ein_Madchen_oder_Weibchen-Die_Zauberflote.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 41,
        "title": "Ehi paggio lonore ladri",
        "composer": "Giuseppe Verdi/威尔第",
        "work": "Falstaff/法斯塔夫",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Ehi_paggio_lonore_ladri-Falstaff.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 40,
        "title": "E fra quest'ansie",
        "composer": "Ruggero Leoncavallo/莱昂卡瓦洛",
        "work": "Pagilacci/丑角",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/E_fra_questansie-Pagilacci.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 39,
        "title": "Donne mie la fate a tanti/我们女人总是这样做",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Così fan tutte, K. 588/女人心",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Donne_mie-Cosi_Fan_Tutte.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 38,
        "title": "Di Provenza/普罗旺斯陆地和海洋",
        "composer": "Giuseppe Verdi/威尔第",
        "work": "La traviata/茶花女",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Di_Provenza-La_traviata.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 37,
        "title": "Der Vogelfänger bin ich ja/我是一个捕鸟人",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Die Zauberflöte, K.620/魔笛",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Der_Vogelfanger_bin_ich_ja-Die_Zauberflote.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 36,
        "title": "Deh vieni alla finestra/请你到窗前来",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Don Giovanni, K.527/唐璜",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Deh_vieni_alla_finestra-Don_Giovanni.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 35,
        "title": "Cruda, funesta smania",
        "composer": "Domenico Gaetano Donizetti/多尼采蒂",
        "work": "Lucia di Lammermoor/拉美莫尔的露琪亚",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Cruda_funesta_smania-Lucia_di_Lammermoor.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 34,
        "title": "Comme une pale fleur",
        "composer": "Ambroise Thomas/托玛",
        "work": "Hamlet/哈姆雷特",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Comme_une_pale_fleur-Hamlet.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 33,
        "title": "Come un'ape ne giorni d'aprile",
        "composer": "Gioachino Rossini/罗西尼",
        "work": "La Cenerentola/灰姑娘",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Come_un_ape_ne_giorni_d_aprile-La_Cenerentola.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 32,
        "title": "Come paride vezzoso",
        "composer": "Domenico Gaetano Donizetti/多尼采蒂",
        "work": "L'Elisir d'Amore/爱的甘醇",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Come_paride_vezzoso-LElisir_dAmore.pdf",
        "date": "2025-12-14",
        "has_lyrics": false
    },
    {
        "id": 31,
        "title": "Bella siccome un angelo/像天使一样美丽",
        "composer": "Domenico Gaetano Donizetti/多尼采蒂",
        "work": "Don Pasquale/唐·帕斯夸勒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Bella_siccome_un_angelo-Don_Pasquale.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 30,
        "title": "Avant de quitter ces lieux/离开故乡去远征",
        "composer": "Charles Gounod/古诺",
        "work": "Faust/浮士德",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Avant_de_quitter_ces_lieux-Faust.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 29,
        "title": "Aprite un po quegli occhi/睁开你们的眼睛",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "Le Nozze di Figaro, K.492/费加罗的婚礼",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Bass-Baritone/低男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Aprite_un_po_quegli_occhi-Le_Nozze_di_Figaro.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 28,
        "title": "Ach wir armen leute",
        "composer": "Engelbert Humperdinck/洪佩尔丁克",
        "work": "Hänsel und Gretel/汉塞尔与格雷特",
        "language": "德语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Ach_wir_armen_Leute-Hansel_und_Gretel.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 27,
        "title": "A quoi bon l'economie",
        "composer": "Jules Massenet/马斯奈",
        "work": "Manon/曼侬",
        "language": "法语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/A_quoi_bon_leconomie-Manon.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 26,
        "title": "Ah! per sempre/啊！我永远失去了你",
        "composer": "Vincenzo Bellini/贝利尼",
        "work": "I Puritanti/清教徒",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "歌剧咏叹调/Ah_per_sempre-I_Puritanti.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 25,
        "title": "Ich habe genung",
        "composer": "J.S. Bach/巴赫",
        "work": "Cantata BWV 82",
        "language": "德语",
        "category": "宗教声乐作品",
        "voice_count": "",
        "voice_types": "Bass/男低音或Bass-Baritone/低男中音",
        "tonality": "",
        "filename": "宗教声乐作品/Ich_habe_genung-bwv_82.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 24,
        "title": "Der Feuerreiter/火焰骑士",
        "composer": "Hugo Wolf/沃尔夫",
        "work": "Mörike-Lieder",
        "language": "德语",
        "category": "艺术歌曲",
        "voice_count": "",
        "voice_types": "",
        "tonality": "g小调",
        "filename": "艺术歌曲/Der_Feuerreiter.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 23,
        "title": "Messiah, HWV 56/弥赛亚",
        "composer": "Georg Friedrich Händel/亨德尔",
        "work": "",
        "language": "英语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "SATB独唱与SATB合唱与管弦乐队",
        "tonality": "",
        "filename": "宗教声乐作品总谱/Messiah_HWV_56_Handel.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 22,
        "title": "War Requiem, Op. 66/战争安魂曲",
        "composer": "Benjamin Britten/布里顿",
        "work": "",
        "language": "拉丁语/英语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "STB独唱与SATB合唱与男童声合唱与管弦乐队及管风琴",
        "tonality": "",
        "filename": "宗教声乐作品总谱/Britten_War_Requiem.pdf",
        "date": "2025-12-14"
    },
    {
        "id": 21,
        "title": "Mass No. 2 in G major, D 167/G大调弥撒",
        "composer": "Franz Schubert/舒伯特",
        "work": "",
        "language": "拉丁语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "STB独唱与SATB合唱与管弦乐队及管风琴",
        "tonality": "G大调",
        "filename": "宗教声乐作品总谱/Schubert_Mass_in_G_Major.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 20,
        "title": "Requiem/安魂曲",
        "composer": "Frederick Delius",
        "work": "",
        "language": "德语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "SB独唱与双合唱队与管弦乐队",
        "tonality": "",
        "filename": "宗教声乐作品总谱/Delius_Requiem.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 19,
        "title": "Requiem, Op. 9/安魂曲",
        "composer": "Maurice Duruflé/杜吕弗莱",
        "work": "",
        "language": "拉丁语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "AB独唱与SATB合唱与管风琴或管弦乐队及管风琴",
        "tonality": "",
        "filename": "宗教声乐作品总谱/Durufle_Requiem.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 17,
        "title": "Requiem in D minor, K. 626/安魂曲",
        "composer": "Wolfgang Amadeus Mozart/莫扎特",
        "work": "",
        "language": "拉丁语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "SATB独唱与SATB合唱与管弦乐队",
        "tonality": "d 小调",
        "filename": "宗教声乐作品总谱/Mozart_Requiem.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 16,
        "title": "Messe de Requiem, Op. 54/安魂曲",
        "composer": "Saint-Saëns/圣桑",
        "work": "",
        "language": "拉丁语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "SATB独唱与SATB合唱与管弦乐队",
        "tonality": "",
        "filename": "宗教声乐作品总谱/Saint-Saens_Requiem.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 15,
        "title": "Requiem in B♭ minor, Op. 89, B. 165/安魂曲",
        "composer": "Antonín Dvořák/德沃夏克",
        "work": "",
        "language": "拉丁语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "SATB独唱与SATB合唱与管弦乐队",
        "tonality": "降b小调",
        "filename": "宗教声乐作品总谱/Dvorak_Requiem.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 14,
        "title": "Requiem in D Minor, Op. 48/安魂曲",
        "composer": "Gabriel Fauré/福雷",
        "work": "",
        "language": "拉丁语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "SB独唱与SATB合唱与管弦乐队和管风琴",
        "tonality": "d 小调",
        "filename": "宗教声乐作品总谱/Faure_Requiem.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 13,
        "title": "Ein deutsches Requiem/德意志安魂曲",
        "composer": "Johannes Brahms/勃拉姆斯",
        "work": "",
        "language": "德语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "SB独唱与SATB合唱与管弦乐队",
        "tonality": "",
        "filename": "宗教声乐作品总谱/Brahms_Requiem.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 12,
        "title": "Cantata BWV 82/Ich habe genug",
        "composer": "J.S. Bach/巴赫",
        "work": "",
        "language": "德语",
        "category": "宗教声乐作品总谱",
        "voice_count": "",
        "voice_types": "",
        "tonality": "",
        "filename": "宗教声乐作品总谱/BWV_82_.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 10,
        "title": "Confrontation",
        "composer": "Claude-Michel Schönberg",
        "work": "Les Misérables/悲惨世界",
        "language": "英语",
        "category": "音乐剧选段",
        "voice_count": "二重唱",
        "voice_types": "TB",
        "tonality": "",
        "filename": "音乐剧选段/confrontation.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 9,
        "title": "Estuans interius",
        "composer": "Carl Orff/奥尔夫",
        "work": "Carmina Burana/布兰诗歌",
        "language": "拉丁语",
        "category": "音乐会咏叹调/世俗康塔塔",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": "",
        "filename": "宗教声乐作品/Estuans_interius-.pdf",
        "date": "2025-12-13",
        "has_lyrics": false
    },
    {
        "id": 8,
        "title": "Pezzo concertato",
        "composer": "Gioachino Rossini/罗西尼",
        "work": "Il viaggio a Reims/兰斯之旅",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "十四重唱/Ensemble",
        "voice_types": "十四重唱/Ensemble",
        "tonality": "",
        "filename": "歌剧重唱/Pezzo_concertato_Il_viaggio_a_Reims.pdf",
        "date": "2025-12-13"
    },
    {
        "id": 7,
        "title": "Pur ti miro",
        "composer": "Claudio Monteverdi/蒙特威尔第",
        "work": "L'incoronazione di Poppea",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "二重唱",
        "voice_types": "CounterTenor or Soprano / Soprano",
        "tonality": "",
        "filename": "歌剧重唱/Duet_Pur_ti_miro_Lincoronazione_di_Poppea.pdf",
        "date": "2025-12-13",
        "has_lyrics": false
    },
    {
        "id": 6,
        "title": "Bella Figlia Dell' Amore",
        "composer": "Giuseppe Verdi/威尔第",
        "work": "Rigoletto/弄臣",
        "language": "意大利语",
        "category": "歌剧重唱",
        "voice_count": "四重唱",
        "voice_types": "Soprano / Contralto / Tenor / Baritone",
        "filename": "歌剧重唱/Rigoletto_Quartet.pdf",
        "date": "2025-12-13",
        "tonality": "",
        "has_lyrics": false
    },
    {
        "id": 5,
        "title": "The Tempest/暴风雨",
        "composer": "Thomas adès",
        "work": "",
        "language": "英语",
        "category": "歌剧总谱",
        "filename": "歌剧总谱/Thomas_ades_.pdf",
        "date": "2025-12-12"
    },
    {
        "id": 4,
        "title": "When I Fly",
        "composer": "Rachel Portman",
        "work": "The Little Prince",
        "language": "英语",
        "category": "歌剧咏叹调",
        "filename": "歌剧咏叹调/When_I_Fly-_The_Little_Prince.pdf",
        "date": "2025-12-12",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": ""
    },
    {
        "id": 3,
        "title": "Herr Oluf",
        "composer": "Carl Loewe",
        "work": "3 Balladen, Op.2",
        "language": "德语",
        "category": "艺术歌曲",
        "filename": "艺术歌曲/Herr_Oluf_Loewe.pdf",
        "date": "2025-12-12",
        "voice_count": "",
        "voice_types": "",
        "tonality": "e小调"
    },
    {
        "id": 2,
        "title": "A Hundred Thousand Stars",
        "composer": "Jake Heggie",
        "work": "Out of Darkness",
        "language": "英语",
        "category": "歌剧咏叹调",
        "filename": "歌剧咏叹调/A_Hundred_Thousand_Stars-Out_of_Darkness.pdf",
        "date": "2025-12-12",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": ""
    },
    {
        "id": 1,
        "title": "E sogno, O realta?/是梦幻，是现实？",
        "composer": "Giuseppe Verdi/威尔第",
        "work": "Falstaff（法斯塔夫）",
        "language": "意大利语",
        "category": "歌剧咏叹调",
        "filename": "歌剧咏叹调/E_sogno_O_realta-Falstaff.pdf",
        "date": "2025-12-12",
        "voice_count": "",
        "voice_types": "Baritone/男中音",
        "tonality": ""
    }
];
const changeLog = [
    {
        "date": "2025-12-16 13:28",
        "type": "update",
        "msg": "更新: Seht auf die breiten"
    },
    {
        "date": "2025-12-16 13:28",
        "type": "update",
        "msg": "更新: Schon eilet froh der ackersmann"
    },
    {
        "date": "2025-12-16 13:28",
        "type": "add",
        "msg": "添加: Seht auf die breiten"
    },
    {
        "date": "2025-12-16 13:27",
        "type": "update",
        "msg": "更新: And God Made The Firmament"
    },
    {
        "date": "2025-12-16 13:27",
        "type": "update",
        "msg": "更新: Rolling in foaming"
    },
    {
        "date": "2025-12-16 13:26",
        "type": "add",
        "msg": "添加: Schon eilet froh der ackersmann"
    },
    {
        "date": "2025-12-16 13:25",
        "type": "add",
        "msg": "添加: Rolling in foaming"
    },
    {
        "date": "2025-12-16 13:24",
        "type": "add",
        "msg": "添加: And God Made The Firmament"
    },
    {
        "date": "2025-12-16 13:22",
        "type": "add",
        "msg": "添加: Komm, süßer tod, BWV 478"
    },
    {
        "date": "2025-12-16 13:21",
        "type": "add",
        "msg": "添加: Mache dich mein herze rein"
    },
    {
        "date": "2025-12-16 13:20",
        "type": "add",
        "msg": "添加: Komm Süßes Kreuz"
    },
    {
        "date": "2025-12-16 13:20",
        "type": "add",
        "msg": "添加: Gebt mir meinen Jesum wieder"
    },
    {
        "date": "2025-12-16 13:17",
        "type": "add",
        "msg": "添加: Et in Spritm Sanctum"
    },
    {
        "date": "2025-12-16 10:07",
        "type": "update",
        "msg": "更新: Belsazar, Op.57"
    },
    {
        "date": "2025-12-16 10:01",
        "type": "add",
        "msg": "添加: Belsazar"
    },
    {
        "date": "2025-12-16 09:57",
        "type": "update",
        "msg": "更新: Am meer/在海边"
    },
    {
        "date": "2025-12-16 09:57",
        "type": "add",
        "msg": "添加: Die beiden Grenadiere/两个禁卫军/两个掷弹兵"
    },
    {
        "date": "2025-12-16 09:54",
        "type": "add",
        "msg": "添加: Am meer/在海边"
    },
    {
        "date": "2025-12-14 23:41",
        "type": "update",
        "msg": "更新: Songs of Travel/旅行之歌"
    },
    {
        "date": "2025-12-14 23:40",
        "type": "update",
        "msg": "更新: A Young Man's Exhortation"
    },
    {
        "date": "2025-12-14 23:37",
        "type": "update",
        "msg": "更新: Ten Blake Songs"
    },
    {
        "date": "2025-12-14 23:37",
        "type": "update",
        "msg": "更新: The House of Life/生命之屋"
    },
    {
        "date": "2025-12-14 23:36",
        "type": "update",
        "msg": "更新: A Shropshire Lad/什罗普郡小伙子"
    },
    {
        "date": "2025-12-14 23:35",
        "type": "update",
        "msg": "更新: A Shropshire Lad/什罗普郡小伙子"
    },
    {
        "date": "2025-12-14 23:21",
        "type": "add",
        "msg": "添加: The House of Life/生命之屋"
    },
    {
        "date": "2025-12-14 23:20",
        "type": "add",
        "msg": "添加: Ten Blake Songs"
    },
    {
        "date": "2025-12-14 23:18",
        "type": "add",
        "msg": "添加: A Shropshire Lad/什罗普郡小伙子"
    },
    {
        "date": "2025-12-14 23:11",
        "type": "add",
        "msg": "添加: Henry Purcell Songs/普赛尔歌曲集"
    },
    {
        "date": "2025-12-14 23:09",
        "type": "add",
        "msg": "添加: A Young Man's Exhortation"
    },
    {
        "date": "2025-12-14 23:06",
        "type": "add",
        "msg": "添加: Baber歌曲集"
    },
    {
        "date": "2025-12-14 23:01",
        "type": "add",
        "msg": "添加: Let us garlands bring"
    },
    {
        "date": "2025-12-14 22:59",
        "type": "add",
        "msg": "添加: Ives 114 Songs"
    },
    {
        "date": "2025-12-14 22:58",
        "type": "add",
        "msg": "添加: Songs of Travel/旅行之歌"
    },
    {
        "date": "2025-12-14 22:50",
        "type": "update",
        "msg": "更新: Or sei pago, o ciel tremendo"
    },
    {
        "date": "2025-12-14 22:50",
        "type": "add",
        "msg": "添加: Sono all'ara…barriera tremenda…Ciel pietoso, in sì crudo momento"
    },
    {
        "date": "2025-12-14 22:50",
        "type": "add",
        "msg": "添加: Or sei pago, o ciel tremendo"
    },
    {
        "date": "2025-12-14 22:49",
        "type": "add",
        "msg": "添加: Sventurata, anch'io deliro"
    },
    {
        "date": "2025-12-14 22:49",
        "type": "add",
        "msg": "添加: Lo sognai ferito, esangue"
    },
    {
        "date": "2025-12-14 22:49",
        "type": "add",
        "msg": "添加: Col sorriso d'innocenza"
    },
    {
        "date": "2025-12-14 22:48",
        "type": "add",
        "msg": "添加: La mia scelta a voi sia grata… Contenta appien quest'alma"
    },
    {
        "date": "2025-12-14 22:48",
        "type": "add",
        "msg": "添加: Deh! Non ferir… Alla gioia ed al piacer"
    },
    {
        "date": "2025-12-14 22:48",
        "type": "add",
        "msg": "添加: Oh! Mie fedeli!...Ma la sola, ohimè! son io…Ah! La pena in lor piombò"
    },
    {
        "date": "2025-12-14 22:47",
        "type": "add",
        "msg": "添加: Dopo l'oscuro nembo"
    },
    {
        "date": "2025-12-14 22:46",
        "type": "add",
        "msg": "添加: È serbato, a questo acciaro"
    },
    {
        "date": "2025-12-14 22:45",
        "type": "add",
        "msg": "添加: Ah! Se non m'ami piu"
    },
    {
        "date": "2025-12-14 22:45",
        "type": "add",
        "msg": "添加: Tu sola… Deh! Tu, deh! Tu, bell'anima"
    },
    {
        "date": "2025-12-14 22:44",
        "type": "add",
        "msg": "添加: Se Romeo l'uccise un figlio"
    },
    {
        "date": "2025-12-14 22:43",
        "type": "add",
        "msg": "添加: Tutto è gioia, tutto è festa"
    },
    {
        "date": "2025-12-14 22:43",
        "type": "add",
        "msg": "添加: De' lieti auguri a voi"
    },
    {
        "date": "2025-12-14 22:42",
        "type": "add",
        "msg": "添加: Sovra il sen la man mi posa"
    }
];
